# Copyright (c) 2020 TK Chia
#
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; ; see the file COPYING.  If not see
# <http://www.gnu.org/licenses/>.

# Configuration file for GitLab (https://gitlab.com/) Continuous Integration.

image: ubuntu:bionic
before_script:
  - apt-get update -y
  - apt-get install -y software-properties-common
  # add-apt-repository may sometimes time out trying to download the PPA's
  # public key.
  - >
      add-apt-repository -y ppa:tkchia/build-ia16 ||
      apt-key add tests/ppa-pub-key.gpg.bin
  - apt-get update -y
  - apt-get install -y gcc-ia16-elf dosemu dos2unix autoconf make bsdutils
test:
  script: ./tests/travis-build-and-check.sh
